<?php

namespace App\Models\Enums;

enum CustomerPrefixPhoneNumberEnum: string
{
    case UK = "+44";
//case USA = "+1";
    case Algeria = "+213";
    case Andorra = "+376";
    case Angola = "+244";
    case Anguilla = "+1264";
    case Antigua_Barbuda = "+1268";
    case Argentina = "+54";
    case Armenia = "+374";
    case Aruba = "+297";
    case Australia = "+61";
    case Austria = "+43";
    case Azerbaijan = "+994";
    case Bahamas = "+1242";
    case Bahrain = "+973";
    case Bangladesh = "+880";
    case Barbados = "+1246";
    case Belarus = "+375";
    case Belgium = "+32";
    case Belize = "+501";
    case Benin = "+229";
    case Bermuda = "+1441";
    case Bhutan = "+975";
    case Bolivia = "+591";
    case Bosni_Herzegovina = "+387";
    case Botswana = "+267";
    case Brazil = "+55";
    case Brunei = "+673";
    case Bulgaria = "+359";
    case Burkina_Faso = "+226";
    case Burundi = "+257";
    case Cambodia = "+855";
    case Cameroon = "+237";
    case Canada = "+1";
    case Cape_Verde_Islands = "+238";
    case Cayman_Islands = "+1345";
    case Central_African_Republic = "+236";
    case Chile = "+56";
    case China = "+86";
    case Colombia = "+57";
//case Comoros= "+269";
    case Congo = "+242";
    case Cook_Islands = "+682";
    case Costa_Rica = "+506";
    case Croatia = "+385";
    case Cuba = "+53";
    case Cyprus_North = "+90392";
    case Cyprus_South = "+357";
    case Czech_Republic = "+42";
    case Denmark = "+45";
    case Djibouti = "+253";
    case Dominica = "+1809";
//case Dominican_Republic= "+1809";
    case Ecuador = "+593";
    case Egypt = "+20";
    case El_Salvador = "+503";
    case Equatorial_Guinea = "+240";
    case Eritrea = "+291";
    case Estonia = "+372";
    case Ethiopia = "+251";
    case Falkland_Islands = "+500";
    case Faroe_Islands = "+298";
    case Fiji = "+679";
    case Finland = "+358";
    case France = "+33";
    case French_Guiana = "+594";
    case French_Polynesia = "+689";
    case Gabon = "+241";
    case Gambia = "+220";
    case Georgia = "+995";
    case Germany = "+49";
    case Ghana = "+233";
    case Gibraltar = "+350";
    case Greece = "+30";
    case Greenland = "+299";
    case Grenada = "+1473";
    case Guadeloupe = "+590";
    case Guam = "+671";
    case Guatemala = "+502";
    case Guinea = "+224";
    case Guinea_Bissau = "+245";
    case Guyana = "+592";
    case Haiti = "+509";
    case Honduras = "+504";
    case Hong_Kong = "+852";
    case Hungary = "+36";
    case Iceland = "+354";
    case India = "+91";
    case Indonesia = "+62";
    case Iran = "+98";
    case Iraq = "+964";
    case Ireland = "+353";
    case Israel = "+972";
    case Italy = "+39";
    case Jamaica = "+1876";
    case Japan = "+81";
    case Jordan = "+962";
//case Kazakhstan= "+7";
    case Kenya = "+254";
    case Kiribati = "+686";
    case Korea_North = "+850";
    case Korea_South = "+82";
    case Kuwait = "+965";
    case Kyrgyzstan = "+996";
    case Laos = "+856";
    case Latvia = "+371";
    case Lebanon = "+961";
    case Lesotho = "+266";
    case Liberia = "+231";
    case Libya = "+218";
    case Liechtenstein = "+417";
    case Lithuania = "+370";
    case Luxembourg = "+352";
    case Macao = "+853";
    case Macedonia = "+389";
    case Madagascar = "+261";
    case Malawi = "+265";
    case Malaysia = "+60";
    case Maldives = "+960";
    case Mali = "+223";
    case Malta = "+356";
    case Marshall_Islands = "+692";
    case Martinique = "+596";
    case Mauritania = "+222";
    case Mayotte = "+269";
    case Mexico = "+52";
    case Micronesia = "+691";
    case Moldova = "+373";
    case Monaco = "+377";
    case Mongolia = "+976";
    case Montserrat = "+1664";
    case Morocco = "+212";
    case Mozambique = "+258";
    case Myanmar = "+95";
    case Namibia = "+264";
    case Nauru = "+674";
    case Nepal = "+977";
    case Netherlands = "+31";
    case New_Caledonia = "+687";
    case New_Zealand = "+64";
    case Nicaragua = "+505";
    case Niger = "+227";
    case Nigeria = "+234";
    case Niue = "+683";
    case Norfolk_Islands = "+672";
    case Northern_Marianas = "+670";
    case Norway = "+47";
    case Oman = "+968";
    case Palau = "+680";
    case Panama = "+507";
    case Papua_New_Guinea = "+675";
    case Paraguay = "+595";
    case Peru = "+51";
    case Philippines = "+63";
    case Poland = "+48";
    case Portugal = "+351";
    case Puerto_Rico = "+1787";
    case Qatar = "+974";
    case Reunion = "+262";
    case Romania = "+40";
//case Russia= "+7";
    case Rwanda = "+250";
    case San_Marino = "+378";
    case Sao_Tome_Principe = "+239";
    case Saudi_Arabia = "+966";
    case Senegal = "+221";
    case Serbia = "+381";
    case Seychelles = "+248";
    case Sierra_Leone = "+232";
    case Singapore = "+65";
    case Slovak_Republic = "+421";
    case Slovenia = "+386";
    case Solomon_Islands = "+677";
    case Somalia = "+252";
    case South_Africa = "+27";
    case Spain = "+34";
    case Sri_Lanka = "+94";
    case St_Helena = "+290";
    case St_Kitts = "+1869";
    case St_Lucia = "+1758";
    case Sudan = "+249";
    case Suriname = "+597";
    case Swaziland = "+268";
    case Sweden = "+46";
    case Switzerland = "+41";
    case Syria = "+963";
    case Taiwan = "+886";
    case Tajikstan = "+7";
    case Thailand = "+66";
    case Togo = "+228";
    case Tonga = "+676";
    case Trinidad_Tobago = "+1868";
    case Tunisia = "+216";
    case Turkey = "+90";
//case Turkmenistan= "+7";
    case Turkmenistan = "+993";
    case Turks_Caicos_Islands = "+1649";
    case Tuvalu = "+688";
    case Uganda = "+256";
    case Ukraine = "+380";
    case United_Arab_Emirates = "+971";
    case Uruguay = "+598";
    case Uzbekistan = "+998";
    case Vanuatu = "+678";
    case Vatican_City = "+379";
    case Venezuela = "+58";
    case Vietnam = "+84";
    case Virgin_Islands_British = "+1284";
    case Virgin_Islands_US = "+1340";
    case Wallis_Futuna = "+681";
    case Yemen_North = "+969";
    case Yemen_South = "+967";
    case Zambia = "+260";
    case Zimbabwe = "+263";

    public static function getEnumByName(string $name): self|null
    {
        foreach (self::cases() as $case) {
            if ($case->value === $name) {
                return $case;
            }
        }
        return null;
    }

    public static function getEnumByValue(string $value): self|null
    {
        foreach (self::cases() as $case) {
            if ($case->name === $value) {
                return $case;
            }
        }
        return null;
    }
}

