services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "true" # or you can use MYSQL_RANDOM_ROOT_PASSWORD: "true"
        ports:
            - "3307:3306"

